
#Format:
#[[trees]]
#id = "sparkling"
#color = [r,g,b]
#
[[trees]]
id = "core_t1"
color = [254, 0xf7, 0x80]
[[trees]]
id = "core_t2"
color = [0x1f, 0x1f, 239]
[[trees]]
id = "core_t3"
color = [0x15, 0x15, 0x15]

[[trees]]
id = "coal"
color = [0, 0, 0]
[[trees]]
id = "iron"
color = [0xb8, 0xb8, 0xb8]
[[trees]]
id = "copper"
color = [0xcd, 0xa6, 0x98]
[[trees]]
id = "gold"
color = [235, 0xd4, 0x50]
[[trees]]
id = "redstone"
color = [0xff, 0x80, 0x80]
[[trees]]
id = "emerald"
color = [0x0, 0xf8, 0x81]
[[trees]]
id = "lapis"
color = [0x3d, 0x6d, 224]
[[trees]]
id = "diamond"
color = [0x46, 0xff, 0xf2]
[[trees]]
id = "quartz"
color = [237, 237, 237]
[[trees]]
id = "ancient"
color = [0xb2, 0xa3, 0x9f]
[[trees]]
id = "clay"
color = [0xcf, 0xd2, 0xd7]
[[trees]]
id = "sand"
color = [0xf0, 0xff, 0x70]
[[trees]]
id = "stone"
color = [0xb9, 0xb9, 0xb9]
[[trees]]
id = "gravel"
color = [0xa0, 0xa0, 0xa0]
[[trees]]
id = "glowstone"
color = [254, 0xdd, 174]
[[trees]]
id = "amethyst"
color = [0xc5, 0xb4, 229]

[[trees]]
id = "desh"
color = [226, 0xb8, 0xa0]
[[trees]]
id = "ice_shard"
color = [0xbc, 0xc7, 0xdd]
[[trees]]
id = "ostrum"
color = [0xc8, 174, 0xb1]
[[trees]]
id = "calorite"
color = [228, 0xa6, 0xa7]
[[trees]]
id = "demonite"
color = [0xd7, 0xf7, 0xf2]
[[trees]]
id = "zinc"
color = [0xdb, 0xf3, 0xdf]
[[trees]]
id = "draconium"
color = [0xc3, 0x92, 232]
[[trees]]
id = "aluminium"
color = [224, 228, 229]
[[trees]]
id = "uranium"
color = [0x92, 174, 0x77]
[[trees]]
id = "osmium"
color = [0xc1, 0xc7, 0xd2]
[[trees]]
id = "fluorite"
color = [0xf5, 0xfd, 0xf9]
[[trees]]
id = "uraninite"
color = [0x80, 0xd1, 0xa2]
[[trees]]
id = "dimensional_shard"
color = [0xbd, 227, 226]
[[trees]]
id = "apatite"
color = [0x8c, 174, 0xc9]
[[trees]]
id = "cinnabar"
color = [0xd4, 0x90, 0x95]
[[trees]]
id = "niter"
color = [0xcd, 0xc5, 0xc6]
[[trees]]
id = "tin"
color = [0xc3, 0xd0, 0xd2]
[[trees]]
id = "lead"
color = [0x91, 0x92, 0xab]
[[trees]]
id = "silver"
color = [0xba, 0xc0, 0xc8]
[[trees]]
id = "nickel"
color = [0xd7, 0xcf, 0xba]
[[trees]]
id = "ruby"
color = [226, 0x8b, 0x9a]
[[trees]]
id = "sapphire"
color = [0x9a, 190, 254]
[[trees]]
id = "cobalt"
color = [0x48, 0x7d, 0xff]
[[trees]]
id = "juperium"
color = [0xaa, 0xd3, 236]
[[trees]]
id = "saturlyte"
color = [0xbb, 0x89, 233]
[[trees]]
id = "neptunium"
color = [0xc0, 0xd3, 0xb5]
[[trees]]
id = "radium"
color = [0xb8, 0xf7, 0xc2]
[[trees]]
id = "plutonium"
color = [254, 0xf9, 0x80]
[[trees]]
id = "electrolyte"
color = [0x91, 0x8a, 228]
[[trees]]
id = "hellforged_parts"
color = [0xd0, 238, 232]
